services:
  - type: web
    name: arasaac-talk
    env: python
    buildCommand: ""
    startCommand: gunicorn 'app:create_app()'
    autoDeploy: true
    envVars:
      - key: FLASK_DEBUG
        value: true
